name: rcp_dashboard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cached_network_image: ^3.4.1
  collapsible_sidebar: ^2.0.7
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  drift: ^2.19.1+1
  file_picker: ^8.1.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.13.0
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  hive_flutter: any
  hydrated_bloc: ^9.0.0
  intl: ^0.19.0
  ionicons: ^0.2.2
  jiffy: ^6.2.1
  json_annotation: ^4.9.0
  logger: any
  path: any
  path_provider: ^2.1.3
  pretty_dio_logger: ^1.3.1
  pretty_qr_code: ^3.3.0
  retrofit: ">=4.1.0"
  rxdart: ^0.28.0
  talker: ^4.4.1
  toast: ^0.3.0
  uuid: ^4.4.2
  window_manager: ^0.4.2

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.19.1

  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.2
  retrofit_generator: ^8.0.6
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/

# flutter_launcher_icons:
#   windows:
#     generate: true
#     image_path: "assets/ico.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "assets/ico.png"
#   image_path: "assets/ico.png"
#   min_sdk_android: 24
flutter_gen:
  output: lib/core/gen/
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
