name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Generate code with build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Run tests
      run: flutter test

    - run: flutter build web --release 
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git --work-tree build/web add --all
    - run: git commit -m "Automatic deployment by github-actions"
    - run: git push origin HEAD:gh-pages --force

   

      
        
        
