name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Generate code with build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Run tests
      run: flutter test

    - name: Build for web
      run: flutter build web

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -f build/web
        git commit -m "Deploy to GitHub Pages"
        git push -f origin `git subtree split --prefix build/web main`:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
